// <auto-generated />
using System;
using LABsistem.Dal.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabSistem.Dal.Migrations
{
    [DbContext(typeof(LabSistemDbContext))]
    [Migration("20260427185134_IncreasePasswordLength")]
    partial class IncreasePasswordLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LABsistem.Domain.Entities.Evidencija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("integer");

                    b.Property<int>("OpremaID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("OpremaID");

                    b.ToTable("Evidencije");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Historija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TerminID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Historije");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.HistorijaTermin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("HistorijaID")
                        .HasColumnType("integer");

                    b.Property<int>("TerminID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("HistorijaTermini");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Kabinet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("KorisnikID")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ObjekatID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("ObjekatID");

                    b.ToTable("Kabineti");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ImePrezime")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Uloga")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.KorisnikObjekat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("KorisnikID")
                        .HasColumnType("integer");

                    b.Property<int>("ObjekatID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("ObjekatID");

                    b.ToTable("KorisnikObjekti");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Obavijest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<bool>("Dostupnost")
                        .HasColumnType("boolean");

                    b.Property<string>("Novosti")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TerminID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("TerminID");

                    b.ToTable("Obavijesti");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Objekat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Lokacija")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RadnoVrijeme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ID");

                    b.ToTable("Objekti");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Oprema", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("KabinetID")
                        .HasColumnType("integer");

                    b.Property<int>("KreatorID")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("SerijskiBroj")
                        .HasColumnType("integer");

                    b.Property<int>("stanje")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("KabinetID");

                    b.ToTable("Oprema");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.OpremaRecenzija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("OpremaID")
                        .HasColumnType("integer");

                    b.Property<int>("RecenzijaID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("OpremaID");

                    b.HasIndex("RecenzijaID");

                    b.ToTable("OpremaRecenzije");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Recenzija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ocjena")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Recenzije");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Termin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KabinetID")
                        .HasColumnType("integer");

                    b.Property<int>("KreatorID")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("VrijemeKraja")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("VrijemePocetka")
                        .HasColumnType("interval");

                    b.HasKey("ID");

                    b.HasIndex("KabinetID");

                    b.HasIndex("KreatorID");

                    b.ToTable("Termini");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Zahtjev", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("KabinetID")
                        .HasColumnType("integer");

                    b.Property<string>("Komentar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<int>("TerminID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("KabinetID");

                    b.HasIndex("TerminID");

                    b.ToTable("Zahtjevi");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Evidencija", b =>
                {
                    b.HasOne("LABsistem.Domain.Entities.Korisnik", "Korisnik")
                        .WithMany("Evidencije")
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LABsistem.Domain.Entities.Oprema", "Oprema")
                        .WithMany("Evidencije")
                        .HasForeignKey("OpremaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Oprema");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Kabinet", b =>
                {
                    b.HasOne("LABsistem.Domain.Entities.Korisnik", "OdgovorniKorisnik")
                        .WithMany("Kabineti")
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LABsistem.Domain.Entities.Objekat", "MaticniObjekat")
                        .WithMany("Kabineti")
                        .HasForeignKey("ObjekatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaticniObjekat");

                    b.Navigation("OdgovorniKorisnik");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.KorisnikObjekat", b =>
                {
                    b.HasOne("LABsistem.Domain.Entities.Korisnik", "Korisnik")
                        .WithMany("KorisnikObjekti")
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LABsistem.Domain.Entities.Objekat", "Objekat")
                        .WithMany("KorisnikObjekti")
                        .HasForeignKey("ObjekatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Objekat");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Obavijest", b =>
                {
                    b.HasOne("LABsistem.Domain.Entities.Termin", "Termin")
                        .WithMany()
                        .HasForeignKey("TerminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Oprema", b =>
                {
                    b.HasOne("LABsistem.Domain.Entities.Kabinet", null)
                        .WithMany("Oprema")
                        .HasForeignKey("KabinetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.OpremaRecenzija", b =>
                {
                    b.HasOne("LABsistem.Domain.Entities.Oprema", "Oprema")
                        .WithMany()
                        .HasForeignKey("OpremaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LABsistem.Domain.Entities.Recenzija", "Recenzija")
                        .WithMany("OpremaRecenzije")
                        .HasForeignKey("RecenzijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oprema");

                    b.Navigation("Recenzija");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Termin", b =>
                {
                    b.HasOne("LABsistem.Domain.Entities.Kabinet", "Kabinet")
                        .WithMany("Termini")
                        .HasForeignKey("KabinetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LABsistem.Domain.Entities.Korisnik", "Kreator")
                        .WithMany("KreiraniTermini")
                        .HasForeignKey("KreatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kabinet");

                    b.Navigation("Kreator");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Zahtjev", b =>
                {
                    b.HasOne("LABsistem.Domain.Entities.Kabinet", "Kabinet")
                        .WithMany()
                        .HasForeignKey("KabinetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LABsistem.Domain.Entities.Termin", "Termin")
                        .WithMany("Zahtjevi")
                        .HasForeignKey("TerminID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kabinet");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Kabinet", b =>
                {
                    b.Navigation("Oprema");

                    b.Navigation("Termini");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Korisnik", b =>
                {
                    b.Navigation("Evidencije");

                    b.Navigation("Kabineti");

                    b.Navigation("KorisnikObjekti");

                    b.Navigation("KreiraniTermini");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Objekat", b =>
                {
                    b.Navigation("Kabineti");

                    b.Navigation("KorisnikObjekti");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Oprema", b =>
                {
                    b.Navigation("Evidencije");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Recenzija", b =>
                {
                    b.Navigation("OpremaRecenzije");
                });

            modelBuilder.Entity("LABsistem.Domain.Entities.Termin", b =>
                {
                    b.Navigation("Zahtjevi");
                });
#pragma warning restore 612, 618
        }
    }
}
