name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore ./Projekat/LabSistem.backend/LabSistem.slnx

      - name: Build
        run: dotnet build ./Projekat/LabSistem.backend/LabSistem.slnx --no-restore

      - name: Test
        run: dotnet test ./Projekat/LABsistem.Tests/LABsistem.Tests.csproj --no-build --logger "console;verbosity=normal"
